package com.example.db.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

@ApiModel(value = "UserPO", description = "")
public class UserPO implements Serializable {
    /**
     * INTEGER(10) 必填
     * 
     */
    @ApiModelProperty(name = "id", value = "")
    private Integer id;

    /**
     * VARCHAR(255)
     * 
     */
    @ApiModelProperty(name = "password", value = "")
    private String password;

    /**
     * VARCHAR(255)
     * 
     */
    @ApiModelProperty(name = "role", value = "")
    private String role;

    /**
     * VARCHAR(255)
     * 
     */
    @ApiModelProperty(name = "status", value = "")
    private String status;

    /**
     * VARCHAR(255)
     * 
     */
    @ApiModelProperty(name = "username", value = "")
    private String username;

    /**
     * BIT(1)
     * 
     */
    @ApiModelProperty(name = "isActivated", value = "")
    private Boolean isActivated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * INTEGER(10) 必填
     * 获得 
     */
    public Integer getId() {
        return id;
    }

    /**
     * INTEGER(10) 必填
     * 设置 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * VARCHAR(255)
     * 获得 
     */
    public String getPassword() {
        return password;
    }

    /**
     * VARCHAR(255)
     * 设置 
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * VARCHAR(255)
     * 获得 
     */
    public String getRole() {
        return role;
    }

    /**
     * VARCHAR(255)
     * 设置 
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * VARCHAR(255)
     * 获得 
     */
    public String getStatus() {
        return status;
    }

    /**
     * VARCHAR(255)
     * 设置 
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * VARCHAR(255)
     * 获得 
     */
    public String getUsername() {
        return username;
    }

    /**
     * VARCHAR(255)
     * 设置 
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * BIT(1)
     * 获得 
     */
    public Boolean getIsActivated() {
        return isActivated;
    }

    /**
     * BIT(1)
     * 设置 
     */
    public void setIsActivated(Boolean isActivated) {
        this.isActivated = isActivated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", password=").append(password);
        sb.append(", role=").append(role);
        sb.append(", status=").append(status);
        sb.append(", username=").append(username);
        sb.append(", isActivated=").append(isActivated);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserPO other = (UserPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getRole() == null ? other.getRole() == null : this.getRole().equals(other.getRole()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getIsActivated() == null ? other.getIsActivated() == null : this.getIsActivated().equals(other.getIsActivated()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getRole() == null) ? 0 : getRole().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getIsActivated() == null) ? 0 : getIsActivated().hashCode());
        return result;
    }
}